---

#############################
#############################
## JavaScript Linter rules ##
#############################
#############################

############
# Env Vars #
############
env:
  browser: true
  jest: true
  node: false        # Node.js global variables and Node.js-specific rules.
  worker: false      # web workers global variables.
  amd: false         # defines require() and define() as global variables as per the amd spec.
  mocha: false       # adds all of the Mocha testing global variables.
  jasmine: false     # adds all of the Jasmine testing global variables for version 1.3 and 2.0.
  phantomjs: false   # phantomjs global variables.
  jquery: false      # jquery global variables.
  prototypejs: false # prototypejs global variables.
  shelljs: false     # shelljs global variables.
  meteor: false      # meteor global variables.
  mongo: false       # mongo global variables.
  applescript: false # applescript global variables.
  es6: false         # enable all ECMAScript 6 features except for modules.

###############
# Global Vars #
###############
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  goog: true

###############
# Parser vars #
###############
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module

###########
# Plugins #
###########
plugins:
  - '@typescript-eslint'

###########
# Extends #
###########
extends:
  - 'eslint:recommended'

#########
# Rules #
#########
rules:
  # Possible Errors
  no-extra-semi: 1            # disallow unnecessary semicolons
  no-inner-declarations: 2    # disallow function or variable declarations in nested blocks

  # Best Practices
  curly: 2                 # specify curly brace conventions for all control statements
  no-eval: 2               # disallow use of eval()
  no-extend-native: 2      # disallow adding to native types
  no-new-wrappers: 2       # disallows creating new instances of String Number and Boolean
  no-with: 2               # disallow use of the with statement

  # Strict Mode

  # Variables
  no-undef: 1              # disallow use of undeclared variables unless mentioned in a /*global */ block
  no-unused-vars: 1

  # Functions
  no-func-assign: ["warn", 2]  

  # Node.js

  # Stylistic Issues
  array-bracket-spacing: ["error", "never"]     # enforce spacing inside array brackets (off by default)
  indent: ["warn", 2]                           # this option sets a specific tab width for your code (off by default)
  no-array-constructor: 2                       # disallow use of the Array constructor
  no-mixed-spaces-and-tabs: 2                   # disallow mixed spaces and tabs for indentation
  no-new-object: 2                              # disallow use of the Object constructor
  semi: 2                                       # require or disallow use of semicolons instead of ASI

  # ECMAScript 6

  # Legacy
  max-len: ["warn", {"code": 80, "tabWidth": 4}]  # specify the maximum length of a line in your program (off by default)
