---
######################
######################
## PR GitHub Action ##
######################
######################
name: Pull-request

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

###########################
# Start the job on all pr #
###########################
on:
  pull_request: {}

###############
# Set the Job #
###############
jobs:
  ################
  # Super Linter #
  ################
  linter:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.yml
          VALIDATE_JAVASCRIPT_STANDARD: false

  ################
  # Semgrep Scan #
  ################
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        auditOn: push
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        publishDeployment: 1076
        
  ###################
  # Sonarcloud Scan #
  ###################
  sonarcloud:
    name: Sonarcloud scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: ./source
        args: >
          -Dsonar.organization=cse110-sp21-group22
          -Dsonar.projectKey=cse110-sp21-group22_cse110-sp21-group22
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  ###################
  # Firebase deploy #
  ###################
  preview:
    needs: [linter, semgrep, sonarcloud]
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CATCH_22_E0C66 }}'
          projectId: catch-22-e0c66
